; generated by sec
target triple = "x86_64-unknown-linux-gnu"

define i32 @main() {
entry:
  %t0 = icmp sgt i32 10, 5
  br i1 %t0, label %if.then.0, label %if.end.1

if.then.0:
  ret i32 3

if.end.1:
  ret i32 4
}

