package llvm

import (
	"strings"
	"testing"

	"sec/internal/ast"
	"sec/internal/lexer"
	"sec/internal/parser"
	"sec/internal/sema"
)

func TestGenerateMinimalMainWithIf(t *testing.T) {
	input := `
module main

fn main() int {
	if true {
		return 0
	}

	return 1
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expected := `; generated by sec
target triple = "` + hostTargetTriple() + `"

define i32 @main() {
entry:
  br i1 true, label %if.then.0, label %if.end.1

if.then.0:
  ret i32 0

if.end.1:
  ret i32 1
}
`

	if strings.TrimSpace(got) != strings.TrimSpace(expected) {
		t.Fatalf("wrong LLVM IR.\nwant:\n%s\n\ngot:\n%s", expected, got)
	}
}

func TestGenerateIntegerLiteralBasesAndSuffixes(t *testing.T) {
	input := `
module main

fn main() int {
	let a: int := 0x8
	let b: uint := 0b1000u
	return a
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`store i32 8`,
		`store i64 8`,
	}
	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateDecimalLiterals(t *testing.T) {
	input := `
module main

fn Pi() decimal {
	return 3.14d
}

fn main() int {
	let a: decimal := 3.14
	let b: decimal := 1
	let c := 2.5d
	let d: decimal := decimal(5)
	return 0
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`%sec.decimal = type { i64, i8 }`,
		`define %sec.decimal @Pi()`,
		`insertvalue %sec.decimal undef, i64 314, 0`,
		`insertvalue %sec.decimal %t0, i8 2, 1`,
		`ret %sec.decimal`,
		`alloca %sec.decimal`,
		`insertvalue %sec.decimal undef, i64 1, 0`,
		`insertvalue %sec.decimal undef, i64 25, 0`,
		`sext i32 5 to i64`,
		`insertvalue %sec.decimal undef, i64 %t`,
		`store %sec.decimal`,
	}
	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateIfElse(t *testing.T) {
	input := `
module main

fn main() int {
	let mut result: int := 0

	if false {
		result = 1
	} else {
		result = 2
	}

	return result
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`br i1 false, label %if.then.`,
		`label %if.else.`,
		`if.else.`,
		`store i32 2`,
		`if.end.`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateShortCircuitIfCondition(t *testing.T) {
	input := `
module main

fn IsReady() bool {
	return true
}

fn main() int {
	if false && IsReady() {
		return 1
	}

	if true || IsReady() {
		return 2
	}

	return 0
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`and.rhs.`,
		`and.false.`,
		`and.end.`,
		`phi i1`,
		`or.true.`,
		`or.rhs.`,
		`or.end.`,
		`call i1 @IsReady()`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestTargetTripleFromHostParts(t *testing.T) {
	tests := []struct {
		goos     string
		goarch   string
		expected string
	}{
		{goos: "linux", goarch: "amd64", expected: "x86_64-pc-linux-gnu"},
		{goos: "linux", goarch: "arm64", expected: "aarch64-pc-linux-gnu"},
		{goos: "darwin", goarch: "amd64", expected: "x86_64-apple-darwin"},
		{goos: "darwin", goarch: "arm64", expected: "aarch64-apple-darwin"},
		{goos: "windows", goarch: "amd64", expected: "x86_64-pc-windows-msvc"},
		{goos: "freebsd", goarch: "amd64", expected: "x86_64-unknown-freebsd"},
	}

	for _, tt := range tests {
		got := targetTriple(tt.goos, tt.goarch)
		if got != tt.expected {
			t.Fatalf("targetTriple(%q, %q) = %q, want %q", tt.goos, tt.goarch, got, tt.expected)
		}
	}
}

func TestGenerateFmtPrintln(t *testing.T) {
	input := `
module main

fn main() int {
	fmt.Println("hello")
	return 0
}
`

	program := parseProgram(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`@.str.0 = private unnamed_addr constant [6 x i8] c"hello\00"`,
		`declare i32 @puts(ptr)`,
		`%t0 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0`,
		`call i32 @puts(ptr %t0)`,
		`ret i32 0`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateRuntimePrintlnString(t *testing.T) {
	input := `
module main

fn Println(value: string) void {
	@runtime.PrintlnString(value)
}

fn main() int {
	Println("hello")
	return 0
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`define void @Println(ptr %value.ptr, i64 %value.len)`,
		`call i32 @puts(ptr %value.ptr)`,
		`call void @Println(ptr`,
		`declare i32 @puts(ptr)`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateSwitch(t *testing.T) {
	input := `
module main

fn main() int {
	switch 7 {
	case < 0:
		return -1
	case 0:
		return 0
	case 1, 2..<10:
		return 10
	default:
		return 20
	}
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`br label %switch.test.1`,
		`icmp slt i32 7, 0`,
		`icmp eq i32 7, 0`,
		`icmp eq i32 7, 1`,
		`icmp sge i32 7, 2`,
		`icmp slt i32 7, 10`,
		`or i1`,
		`define i32 @main()`,
		`ret i32 10`,
		`ret i32 20`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateDescendingSwitchRange(t *testing.T) {
	input := `
module main

fn main() int {
	switch 7 {
	case 10..0:
		return 1
	default:
		return 0
	}
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`icmp sgt i32 10, 0`,
		`icmp sge i32 7, 0`,
		`icmp sle i32 7, 10`,
		`select i1`,
		`ret i32 1`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateSwitchAssignmentsToLocal(t *testing.T) {
	input := `
module main

fn main() int {
	let mut result: int

	switch 7 {
	case < 0:
		result = -1
	case 0:
		result = 0
	case 1, 2..<10:
		result = 10
	default:
		result = 20
	}

	return result
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`alloca i32`,
		`store i32 10`,
		`store i32 20`,
		`load i32`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateInlineAsmSysWriteFunction(t *testing.T) {
	input := `
module main

fn _sysWrite(fd: int64, ref ptr: byte, len: int64) int64 {
	unsafe {
		asm {
			"syscall"
			inputs: rax(1), rdi(fd), rsi(ptr), rdx(len)
			outputs: rax
		}
	}
}

fn main() int {
	return 0
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`define i64 @_sysWrite(i64 %fd, ptr %ptr, i64 %len)`,
		`ptrtoint ptr %ptr to i64`,
		`call i64 asm sideeffect "syscall", "={rax},{rax},{rdi},{rsi},{rdx},~{rcx},~{r11}"`,
		`ret i64`,
		`define i32 @main()`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateUnsafeFunctionWithNamedAsmOutput(t *testing.T) {
	input := `
module main

unsafe fn _rawSyscall3(number: uint, arg1: uint, arg2: uint, arg3: uint) int {
	asm {
		"syscall"

		inputs:
			rax(number)
			rdi(arg1)
			rsi(arg2)
			rdx(arg3)

		outputs:
			rax(result)

		clobbers:
			rcx
			r11
			memory
	}

	return result
}

fn main() int {
	return 0
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`define i32 @_rawSyscall3(i64 %number, i64 %arg1, i64 %arg2, i64 %arg3)`,
		`call i64 asm sideeffect "syscall", "={rax},{rax},{rdi},{rsi},{rdx},~{rcx},~{r11},~{memory}"`,
		`trunc i64`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGeneratePrintlnWithStringPtrAndLen(t *testing.T) {
	input := `
module main

fn _sysWrite(fd: int64, ref ptr: byte, len: int64) int64 {
	unsafe {
		asm {
			"syscall"
			inputs: rax(1), rdi(fd), rsi(ptr), rdx(len)
			outputs: rax
		}
	}
}

fn Println(s: string) void {
	_sysWrite(1, s.ptr, s.len)

	let nl := "\n"
	_sysWrite(1, nl.ptr, 1)
}

fn main() int {
	Println("hello")
	return 0
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`define void @Println(ptr %s.ptr, i64 %s.len)`,
		`call i64 @_sysWrite(i64`,
		`ptr %s.ptr, i64 %s.len`,
		`private unnamed_addr constant [2 x i8] c"\0A\00"`,
		`call void @Println(ptr`,
		`i64 5`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateRangeForLoop(t *testing.T) {
	input := `
module main

fn main() int {
	let mut sum: int := 0

	for i in 0..<3 {
		if i == 2 {
			continue
		}
		sum += i
	}

	return sum
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`for.condition`,
		`for.body`,
		`for.next`,
		`for.end`,
		`icmp slt i32`,
		`add i32`,
		`br label %for.next`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateWhileLoop(t *testing.T) {
	input := `
module main

fn main() int {
	let mut i: int := 0
	let mut sum: int := 0

	while i < 5 {
		i += 1
		if i == 3 {
			continue
		}
		if i == 5 {
			break
		}
		sum += i
	}

	return sum
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`while.condition`,
		`while.body`,
		`while.end`,
		`icmp slt i32`,
		`br label %while.condition`,
		`br label %while.end`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateRangeForLoopWithBreak(t *testing.T) {
	input := `
module main

fn main() int {
	let mut result: int := 0

	for i in 0..10 {
		if i == 3 {
			break
		}
		result = i
	}

	return result
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`icmp sle i32`,
		`br label %for.end`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateDescendingRangeForLoop(t *testing.T) {
	input := `
module main

fn main() int {
	let mut sum: int := 0

	for i in 10..0 {
		sum += i
	}

	return sum
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`icmp sgt i32 10, 0`,
		`icmp sge i32`,
		`sub i32`,
		`select i1`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateRangeForLoopWithExplicitStep(t *testing.T) {
	input := `
module main

fn main() int {
	let mut sum: int := 0

	for i in 0..<10 step 2 {
		sum += i
	}

	return sum
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`add i32`,
		`, 2`,
		`sub i32`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateInfiniteForLoop(t *testing.T) {
	input := `
module main

fn main() int {
	let mut result: int := 0

	for {
		result = 1
		break
	}

	return result
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`for.body`,
		`for.end`,
		`br label %for.body`,
		`br label %for.end`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateNonCapturingLambdaCall(t *testing.T) {
	input := `
module main

fn main() int {
	let double := fn(value: int) int {
		return value * 2
	}

	return double(10)
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`define i32 @__sec_lambda_0(i32 %value)`,
		`mul i32 %value, 2`,
		`store ptr @__sec_lambda_0`,
		`load ptr`,
		`call i32 %`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateNamedFunctionValueCall(t *testing.T) {
	input := `
module main

fn IsPositive(value: int) bool {
	return value > 0
}

fn main() int {
	let predicate := IsPositive
	if predicate(10) {
		return 0
	}
	return 1
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`define i1 @IsPositive(i32 %value)`,
		`store ptr @IsPositive`,
		`call i1 %`,
		`ret i32 0`,
		`ret i32 1`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateEnumMatchExpression(t *testing.T) {
	input := `
module main

enum Color {
	red,
	green,
	blue,
}

fn main() int {
	let color: Color := Color.green
	let code := match color {
		Color.red => 1
		Color.green => 2
		Color.blue => 3
	}

	return code
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`store i32 1, ptr`,
		`icmp eq i32`,
		`match.arm.`,
		`match.test.`,
		`match.end.`,
		`store i32 2`,
		`load i32`,
		`ret i32`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func TestGenerateEnumMatchStatementWithBlocks(t *testing.T) {
	input := `
module main

enum Color {
	red,
	green,
}

fn main() int {
	let color: Color := Color.red

	match color {
		Color.red => return 1
		_ => return 2
	}
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`match.arm.`,
		`match.test.`,
		`icmp eq i32`,
		`ret i32 1`,
		`ret i32 2`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func parseProgram(t *testing.T, input string) *ast.Program {
	t.Helper()

	l := lexer.New(input)
	p := parser.New(l)
	program := p.ParseProgram()
	if len(p.Errors()) > 0 {
		t.Fatalf("parse errors: %v", p.Errors())
	}
	return program
}

func parseAndAnalyze(t *testing.T, input string) *ast.Program {
	t.Helper()

	program := parseProgram(t, input)

	analyzer := sema.NewAnalyzer()
	if errors := analyzer.Analyze(program); len(errors) > 0 {
		t.Fatalf("sema errors: %v", errors)
	}

	return program
}
