package llvm

import (
	"fmt"
	"strings"

	"sec/internal/ast"
)

type Generator struct {
	out       strings.Builder
	globals   strings.Builder
	label     int
	temp      int
	stringID  int
	needsPuts bool
	blockOpen bool
}

func NewGenerator() *Generator {
	return &Generator{}
}

func Generate(program *ast.Program) (string, error) {
	return NewGenerator().Generate(program)
}

func (g *Generator) Generate(program *ast.Program) (string, error) {
	if err := validateEntrypoint(program); err != nil {
		return "", err
	}

	for _, stmt := range program.Statements {
		fn, ok := stmt.(*ast.FunctionDeclaration)
		if !ok || fn.Name == nil || fn.Name.Value != "main" {
			continue
		}
		if err := g.emitFunction(fn); err != nil {
			return "", err
		}
	}

	var result strings.Builder
	result.WriteString("; generated by sec\n")
	result.WriteString("target triple = \"x86_64-unknown-linux-gnu\"\n\n")
	result.WriteString(g.globals.String())
	if g.globals.Len() > 0 {
		result.WriteString("\n")
	}
	if g.needsPuts {
		result.WriteString("declare i32 @puts(ptr)\n\n")
	}
	result.WriteString(g.out.String())
	return result.String(), nil
}

func validateEntrypoint(program *ast.Program) error {
	hasMainModule := false
	for _, stmt := range program.Statements {
		module, ok := stmt.(*ast.ModuleStatement)
		if ok && module.Path == "main" {
			hasMainModule = true
			break
		}
	}
	if !hasMainModule {
		return fmt.Errorf("emit-llvm requires module main")
	}

	mainFn := findMainFunction(program)
	if mainFn == nil {
		return fmt.Errorf("emit-llvm requires fn main() int or fn main() void")
	}
	if len(mainFn.Parameters) != 0 {
		return fmt.Errorf("emit-llvm requires fn main() with no parameters")
	}
	if mainFn.ReturnType == nil || (mainFn.ReturnType.Name != "int" && mainFn.ReturnType.Name != "void") {
		return fmt.Errorf("emit-llvm requires fn main() int or fn main() void")
	}

	return nil
}

func findMainFunction(program *ast.Program) *ast.FunctionDeclaration {
	for _, stmt := range program.Statements {
		fn, ok := stmt.(*ast.FunctionDeclaration)
		if ok && fn.Name != nil && fn.Name.Value == "main" {
			return fn
		}
	}
	return nil
}

func (g *Generator) write(format string, args ...any) {
	fmt.Fprintf(&g.out, format, args...)
}

func (g *Generator) nextLabel(prefix string) string {
	name := fmt.Sprintf("%s.%d", prefix, g.label)
	g.label++
	return name
}

func (g *Generator) nextTemp() string {
	name := fmt.Sprintf("%%t%d", g.temp)
	g.temp++
	return name
}
