package llvm

import (
	"fmt"
	"runtime"
	"strings"

	"sec/internal/ast"
)

type Generator struct {
	out          strings.Builder
	lambdaDefs   strings.Builder
	activeOut    *strings.Builder
	globals      strings.Builder
	label        int
	temp         int
	stringID     int
	lambdaID     int
	needsPuts    bool
	needsDecimal bool
	locals       map[string]local
	functions    map[string]*ast.FunctionDeclaration
	typeAliases  map[string]*ast.TypeReference
	enums        map[string]enumInfo
	loops        []loopContext
	returnType   string
	targetTriple string
	blockOpen    bool
}

type loopContext struct {
	breakLabel    string
	continueLabel string
}

type local struct {
	typ    string
	ptr    string
	ref    string
	lenRef string
	fnType *ast.TypeReference
	direct bool
}

type enumInfo struct {
	typ    string
	values map[string]string
}

func NewGenerator() *Generator {
	return &Generator{}
}

func Generate(program *ast.Program) (string, error) {
	return NewGenerator().Generate(program)
}

func GenerateWithTriple(program *ast.Program, triple string) (string, error) {
	g := NewGenerator()
	g.targetTriple = triple
	return g.Generate(program)
}

func (g *Generator) Generate(program *ast.Program) (string, error) {
	if err := validateEntrypoint(program); err != nil {
		return "", err
	}
	g.functions = map[string]*ast.FunctionDeclaration{}
	g.typeAliases = map[string]*ast.TypeReference{}
	g.enums = map[string]enumInfo{}
	for _, stmt := range program.Statements {
		switch stmt := stmt.(type) {
		case *ast.FunctionDeclaration:
			if stmt.Name != nil {
				g.functions[stmt.Name.Value] = stmt
			}
		case *ast.TypeDeclStatement:
			g.registerTypeDeclaration(stmt, "")
		case *ast.EnumDeclaration:
			g.registerEnum(stmt, "")
		case *ast.ImplStatement:
			target := ""
			if stmt.Target != nil {
				target = stmt.Target.Name
			}
			for _, member := range stmt.Members {
				if typeDecl, ok := member.(*ast.TypeDeclStatement); ok {
					g.registerTypeDeclaration(typeDecl, target)
				}
				if enumDecl, ok := member.(*ast.EnumDeclaration); ok {
					g.registerEnum(enumDecl, target)
				}
			}
		}
	}

	for _, stmt := range program.Statements {
		fn, ok := stmt.(*ast.FunctionDeclaration)
		if !ok || fn.Name == nil {
			continue
		}
		if err := g.emitFunction(fn); err != nil {
			return "", err
		}
	}

	var result strings.Builder
	result.WriteString("; generated by sec\n")
	triple := g.targetTriple
	if triple == "" {
		triple = hostTargetTriple()
	}
	result.WriteString(fmt.Sprintf("target triple = %q\n\n", triple))
	if g.needsDecimal {
		result.WriteString(llvmDecimalType + " = type { i64, i8 }\n\n")
	}
	result.WriteString(g.globals.String())
	if g.globals.Len() > 0 {
		result.WriteString("\n")
	}
	if g.needsPuts {
		result.WriteString("declare i32 @puts(ptr)\n\n")
	}
	result.WriteString(g.lambdaDefs.String())
	result.WriteString(g.out.String())
	return result.String(), nil
}

func hostTargetTriple() string {
	return targetTriple(runtime.GOOS, runtime.GOARCH)
}

func targetTriple(goos string, goarch string) string {
	arch := llvmTargetArch(goarch)

	switch goos {
	case "linux":
		return arch + "-pc-linux-gnu"
	case "darwin", "macos":
		return arch + "-apple-darwin"
	case "windows":
		return arch + "-pc-windows-msvc"
	case "freebsd":
		return arch + "-unknown-freebsd"
	case "openbsd":
		return arch + "-unknown-openbsd"
	case "netbsd":
		return arch + "-unknown-netbsd"
	default:
		return arch + "-unknown-" + goos
	}
}

func llvmTargetArch(goarch string) string {
	switch goarch {
	case "amd64":
		return "x86_64"
	case "386":
		return "i386"
	case "arm64":
		return "aarch64"
	case "arm", "arm32":
		return "arm"
	case "riscv64":
		return "riscv64"
	default:
		return goarch
	}
}

func validateEntrypoint(program *ast.Program) error {
	hasMainModule := false
	for _, stmt := range program.Statements {
		module, ok := stmt.(*ast.ModuleStatement)
		if ok && module.Path == "main" {
			hasMainModule = true
			break
		}
	}
	if !hasMainModule {
		return fmt.Errorf("emit-llvm requires module main")
	}

	mainFn := findMainFunction(program)
	if mainFn == nil {
		return fmt.Errorf("emit-llvm requires fn main() int or fn main() void")
	}
	if len(mainFn.Parameters) != 0 {
		return fmt.Errorf("emit-llvm requires fn main() with no parameters")
	}
	if mainFn.ReturnType == nil || (mainFn.ReturnType.Name != "int" && mainFn.ReturnType.Name != "void") {
		return fmt.Errorf("emit-llvm requires fn main() int or fn main() void")
	}

	return nil
}

func findMainFunction(program *ast.Program) *ast.FunctionDeclaration {
	for _, stmt := range program.Statements {
		fn, ok := stmt.(*ast.FunctionDeclaration)
		if ok && fn.Name != nil && fn.Name.Value == "main" {
			return fn
		}
	}
	return nil
}

func (g *Generator) write(format string, args ...any) {
	if g.activeOut != nil {
		fmt.Fprintf(g.activeOut, format, args...)
		return
	}
	fmt.Fprintf(&g.out, format, args...)
}

func (g *Generator) nextLabel(prefix string) string {
	name := fmt.Sprintf("%s.%d", prefix, g.label)
	g.label++
	return name
}

func (g *Generator) nextTemp() string {
	name := fmt.Sprintf("%%t%d", g.temp)
	g.temp++
	return name
}
