package llvm

import (
	"strings"
	"testing"

	"sec/internal/ast"
	"sec/internal/lexer"
	"sec/internal/parser"
	"sec/internal/sema"
)

func TestGenerateMinimalMainWithIf(t *testing.T) {
	input := `
module main

fn main() int {
	if true {
		return 0
	}

	return 1
}
`

	program := parseAndAnalyze(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expected := `; generated by sec
target triple = "x86_64-unknown-linux-gnu"

define i32 @main() {
entry:
  br i1 true, label %if.then.0, label %if.end.1

if.then.0:
  ret i32 0

if.end.1:
  ret i32 1
}
`

	if strings.TrimSpace(got) != strings.TrimSpace(expected) {
		t.Fatalf("wrong LLVM IR.\nwant:\n%s\n\ngot:\n%s", expected, got)
	}
}

func TestGenerateFmtPrintln(t *testing.T) {
	input := `
module main

fn main() int {
	fmt.Println("hello")
	return 0
}
`

	program := parseProgram(t, input)
	got, err := Generate(program)
	if err != nil {
		t.Fatalf("Generate returned error: %v", err)
	}

	expectedParts := []string{
		`@.str.0 = private unnamed_addr constant [6 x i8] c"hello\00"`,
		`declare i32 @puts(ptr)`,
		`%t0 = getelementptr inbounds [6 x i8], ptr @.str.0, i64 0, i64 0`,
		`call i32 @puts(ptr %t0)`,
		`ret i32 0`,
	}

	for _, part := range expectedParts {
		if !strings.Contains(got, part) {
			t.Fatalf("generated LLVM IR missing %q.\nIR:\n%s", part, got)
		}
	}
}

func parseProgram(t *testing.T, input string) *ast.Program {
	t.Helper()

	l := lexer.New(input)
	p := parser.New(l)
	program := p.ParseProgram()
	if len(p.Errors()) > 0 {
		t.Fatalf("parse errors: %v", p.Errors())
	}
	return program
}

func parseAndAnalyze(t *testing.T, input string) *ast.Program {
	t.Helper()

	program := parseProgram(t, input)

	analyzer := sema.NewAnalyzer()
	if errors := analyzer.Analyze(program); len(errors) > 0 {
		t.Fatalf("sema errors: %v", errors)
	}

	return program
}
