package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"unicode"
)

type letterRange struct {
	start  uint32
	end    uint32
	stride uint32
}

func main() {
	output := flag.String("output", "sec/stdlib/unicode/unicode.sec", "generated Sec source path")
	flag.Parse()
	if err := os.MkdirAll(filepath.Dir(*output), 0755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, renderLetterTables(), 0644); err != nil {
		panic(err)
	}
}

func unicodeLetterRanges() []letterRange {
	raw := make([]letterRange, 0, len(unicode.Letter.R16)+len(unicode.Letter.R32))
	for _, value := range unicode.Letter.R16 {
		raw = append(raw, letterRange{start: uint32(value.Lo), end: uint32(value.Hi), stride: uint32(value.Stride)})
	}
	for _, value := range unicode.Letter.R32 {
		raw = append(raw, letterRange{start: value.Lo, end: value.Hi, stride: value.Stride})
	}
	ranges := make([]letterRange, 0, len(raw))
	for _, value := range raw {
		if value.stride == 1 {
			ranges = append(ranges, value)
			continue
		}
		for codePoint := value.start; codePoint <= value.end; codePoint += value.stride {
			ranges = append(ranges, letterRange{start: codePoint, end: codePoint, stride: 1})
		}
	}
	return ranges
}

func renderLetterTables() []byte {
	ranges := unicodeLetterRanges()
	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by go run ./cmd/unicodegen. DO NOT EDIT.")
	fmt.Fprintf(&out, "// Source: Go unicode.Letter, Unicode %s.\n\n", unicode.Version)
	fmt.Fprintln(&out, "module unicode")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "type LetterRange struct {")
	fmt.Fprintln(&out, "    start: rune,")
	fmt.Fprintln(&out, "    end: rune,")
	fmt.Fprintln(&out, "}")
	fmt.Fprintln(&out)
	fmt.Fprintf(&out, "let letterRanges: LetterRange[%d] := [\n", len(ranges))
	for _, value := range ranges {
		fmt.Fprintf(&out, "    LetterRange{ start: 0x%06Xr, end: 0x%06Xr },\n", value.start, value.end)
	}
	fmt.Fprintln(&out, "]")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "/** Reports whether ch is a Unicode letter. */")
	fmt.Fprintln(&out, "fn IsLetter(ch: rune) bool {")
	fmt.Fprintln(&out, "    if ch < 0r || ch > 0x10FFFFr {")
	fmt.Fprintln(&out, "        return false")
	fmt.Fprintln(&out, "    }")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "    if ch <= 0x007Fr {")
	fmt.Fprintln(&out, "        return (ch >= 0x0041r && ch <= 0x005Ar) ||")
	fmt.Fprintln(&out, "            (ch >= 0x0061r && ch <= 0x007Ar)")
	fmt.Fprintln(&out, "    }")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "    let mut low := 0")
	fmt.Fprintf(&out, "    let mut high := %d\n", len(ranges)-1)
	fmt.Fprintln(&out, "    while low <= high {")
	fmt.Fprintln(&out, "        let middle := low + (high - low) / 2")
	fmt.Fprintln(&out, "        let current := letterRanges[middle]")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "        if ch < current.start {")
	fmt.Fprintln(&out, "            high = middle - 1")
	fmt.Fprintln(&out, "            continue")
	fmt.Fprintln(&out, "        }")
	fmt.Fprintln(&out, "        if ch > current.end {")
	fmt.Fprintln(&out, "            low = middle + 1")
	fmt.Fprintln(&out, "            continue")
	fmt.Fprintln(&out, "        }")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "        return true")
	fmt.Fprintln(&out, "    }")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "    return false")
	fmt.Fprintln(&out, "}")
	return out.Bytes()
}

func tableContains(ranges []letterRange, value rune) bool {
	if value < 0 || value > unicode.MaxRune {
		return false
	}
	low := 0
	high := len(ranges) - 1
	for low <= high {
		middle := low + (high-low)/2
		current := ranges[middle]
		if uint32(value) < current.start {
			high = middle - 1
			continue
		}
		if uint32(value) > current.end {
			low = middle + 1
			continue
		}
		return true
	}
	return false
}
