// Command confusablesgen generates the UTS #39 confusable prototype table used
// by identifier-confusability checks from the pinned Unicode confusables.txt.
//
// Rules:
//   - rules/foundations/lexical_structure.md — "Visually confusable identifiers"
//   - rules/corrections/applied/missing-decisions-md001-md009-correction-20261003.md — §§ 2.1–2.4
package main

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

func main() {
	input := flag.String("input", "third_party/unicode/15.0.0/confusables.txt", "Unicode confusables.txt source")
	output := flag.String("output", "internal/lexer/confusables_table.go", "generated Go table path")
	flag.Parse()
	source, err := os.Open(*input)
	if err != nil {
		panic(err)
	}
	defer source.Close()
	version, mappings, err := parseConfusables(source)
	if err != nil {
		panic(err)
	}
	formatted, err := format.Source(renderTable(version, mappings))
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile(*output, formatted, 0644); err != nil {
		panic(err)
	}
}

// parseConfusables reads the data version and every single-code-point
// prototype mapping. Each mapping line has the form
// `source ; target sequence ; type # comment`.
func parseConfusables(source io.Reader) (string, map[rune]string, error) {
	scanner := bufio.NewScanner(source)
	scanner.Buffer(make([]byte, 64*1024), 1024*1024)
	version := ""
	mappings := map[rune]string{}
	for scanner.Scan() {
		line := strings.TrimPrefix(scanner.Text(), "\uFEFF")
		if strings.HasPrefix(line, "# Version:") {
			version = strings.TrimSpace(strings.TrimPrefix(line, "# Version:"))
			continue
		}
		if comment := strings.IndexByte(line, '#'); comment >= 0 {
			line = line[:comment]
		}
		fields := strings.Split(line, ";")
		if len(fields) < 3 {
			continue
		}
		from, err := parseCodePoints(fields[0])
		if err != nil || len(from) != 1 {
			return "", nil, fmt.Errorf("invalid confusable source %q", fields[0])
		}
		to, err := parseCodePoints(fields[1])
		if err != nil || len(to) == 0 {
			return "", nil, fmt.Errorf("invalid confusable target %q", fields[1])
		}
		mappings[from[0]] = string(to)
	}
	if err := scanner.Err(); err != nil {
		return "", nil, err
	}
	if version == "" {
		return "", nil, fmt.Errorf("confusables data has no version header")
	}
	return version, mappings, nil
}

func parseCodePoints(field string) ([]rune, error) {
	values := []rune{}
	for _, part := range strings.Fields(field) {
		value, err := strconv.ParseUint(part, 16, 32)
		if err != nil {
			return nil, err
		}
		values = append(values, rune(value))
	}
	return values, nil
}

func renderTable(version string, mappings map[rune]string) []byte {
	keys := make([]rune, 0, len(mappings))
	for key := range mappings {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	var out bytes.Buffer
	fmt.Fprintf(&out, "// Code generated by cmd/confusablesgen from third_party/unicode/%s/confusables.txt. DO NOT EDIT.\n\n", version)
	out.WriteString("package lexer\n\n")
	fmt.Fprintf(&out, "// ConfusableDataVersion is the Unicode version of the UTS #39 confusable data.\n")
	fmt.Fprintf(&out, "const ConfusableDataVersion = %q\n\n", version)
	out.WriteString("// confusablePrototypes maps a code point to its UTS #39 prototype sequence.\n")
	out.WriteString("var confusablePrototypes = map[rune]string{\n")
	for _, key := range keys {
		fmt.Fprintf(&out, "\t0x%04X: %q,\n", key, mappings[key])
	}
	out.WriteString("}\n")
	return out.Bytes()
}
